spring:
  application:
    name: vegetable-backend


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://10.168.1.20:3306/vegetable
server:
  servlet:
    context-path: /api
  port: 8125


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '接口文档'
      paths-to-match: '/**'
      packages-to-scan: com.wj.vegetablebackend.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn